image: docker:stable

services:
  - docker:stable-dind

variables:
  IMAGE_HASH: qdevelopment/issuer-svc:$CI_COMMIT_SHA
  IMAGE_TAG: qdevelopment/issuer-svc:$CI_COMMIT_TAG
  IMAGE_LATEST: qdevelopment/issuer-svc:latest

stages:
  - build

.before_script_template:
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf https://gitlab.com/
    - echo "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc
    - go env -w GOPRIVATE=gitlab.com/*
    - go env -w GONOSUMDB=gitlab.com/*
    - go env -w GONOPROXY=gitlab.com/*

.docker-login: &docker-login
  before_script:
    - echo "$REGISTRY_PASS" | docker login --username $REGISTRY_USER --password-stdin

build:
  <<: [*docker-login]
  stage: build
  extends: .before_script_template
  script:
    - docker build -t $IMAGE_HASH . --build-arg BUILD_TOKEN=$CI_JOB_TOKEN --build-arg USERNAME="gitlab-ci-token"
    - docker push $IMAGE_HASH

release:
  <<: [*docker-login]
  stage: build
  only:
   - tags
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
